export const REQUEST_EVENT_DATA = 'REQUEST_EVENT_DATA'
export const SHOW_EVENT_DATA = 'SHOW_EVENT_DATA'
export const FAILED_GET_EVENT_DATA = 'FAILED_GET_EVENT_DATA'
export const SUCCESS_EVENT_DATA = 'SUCCESS_EVENT_DATA'