export const REQUEST_EVENT_ITEM = 'REQUEST_EVENT_ITEM'
export const SHOW_EVENT_ITEM = 'SHOW_EVENT_ITEM'
export const FAILED_GET_EVENT_ITEM = 'FAILED_GET_EVENT_ITEM'
export const SUCCESS_EVENT_ITEM = 'SUCCESS_EVENT_ITEM'